/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-01-11 11:32:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("	<title></title>\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\" src=\"js/lib/jquery-latest.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"js/lib/jquery-ui-latest.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"js/lib/themeswitchertool.js\"></script>\n");
      out.write("	<script type=\"text/javascript\" src=\"js/lib/jquery.cookies.min.js\"></script>\n");
      out.write("	\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		//if(navigator.platform.indexOf('iPad') != -1) {\n");
      out.write("		if( /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent) ) {\n");
      out.write("			$.get(\"do/IOviyamContext\", function(data) {\n");
      out.write("				var loc = window.location.toString();\n");
      out.write("				loc = loc.substring(0, loc.indexOf('/', loc.lastIndexOf(':')));\n");
      out.write("				window.location = loc + data;\n");
      out.write("				//window.stop();\n");
      out.write("			   });\n");
      out.write("		}   	   \n");
      out.write("		\n");
      out.write("		var lang = $.cookies.get( 'language' );\n");
      out.write("		var bundleName = '';\n");
      out.write("		if (lang == null || lang.trim() == 'en_GB') {\n");
      out.write("			bundleName = 'js/i18n/Bundle.js'; \n");
      out.write("		} else {\n");
      out.write("			bundleName = 'js/i18n/' + \"Bundle_\" + lang + \".js\";\n");
      out.write("		}			\n");
      out.write("		document.write('<script type=\"text/javascript\" src=\"' + bundleName + '\"><\\/script>');\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("	<link rel=\"icon\" type=\"image/png\" href=\"images/favicon.png\"/>\n");
      out.write("	<link rel=\"stylesheet\" href=\"css/login.css\" type=\"text/css\" />\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery.ui.all.css\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		$(document).ready(function() {\n");
      out.write("			var theme = $.cookies.get( 'theme' );\n");
      out.write("			if(theme == null) {\n");
      out.write("				theme = 'Dark Hive';\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			var browserVersion= navigator.userAgent.match(/(opera|chrome|safari|firefox|msie)\\/?\\s*(\\.?\\d+(\\.\\d+)*)/i);\n");
      out.write("			var browserName = browserVersion[1].toUpperCase();\n");
      out.write("			/*if( !(browserName != 'CHROME' && browserName != 'SAFARI') ) {\n");
      out.write("				$('footer').remove();\n");
      out.write("			}*/\n");
      out.write("			if(!(browserName.indexOf('MSIE')>0)) {\n");
      out.write("				$('footer').remove();\n");
      out.write("			}            		\n");
      out.write("			\n");
      out.write("			$('#switcher').themeswitcher({\n");
      out.write("						loadTheme: theme,\n");
      out.write("						cookieName:'',\n");
      out.write("						width: 160\n");
      out.write("			});\n");
      out.write("	\n");
      out.write("			$('#loginButton').button();\n");
      out.write("				$(document).attr('title', languages['PageTitle']);\n");
      out.write("				$(\"#loginButton\").val(languages['Login']);\n");
      out.write("			});  \n");
      out.write("\n");
      out.write("		function setCookie(name, value, expires, path, domain, secure) {\n");
      out.write("			  var curCookie = name + \"=\" + escape(value) +\n");
      out.write("			  ((expires) ? \"; expires=\" + expires.toUTCString() : \"\") +\n");
      out.write("			  ((path) ? \"; path=\" + path : \"\") +\n");
      out.write("			  ((domain) ? \"; domain=\" + domain : \"\") +\n");
      out.write("			  ((secure) ? \"; secure\" : \"\");\n");
      out.write("			  document.cookie = curCookie;\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function validateForm(form) {\n");
      out.write("			if(form.remember_me.checked) {\n");
      out.write("				  var credentials = {\n");
      out.write("					  'username' : form.j_username.value,\n");
      out.write("					  'password' : form.j_password.value,\n");
      out.write("					  'remember': form.remember_me.checked\n");
      out.write("				  };\n");
      out.write("				  setCookie(\"credentials\",JSON.stringify(credentials));\n");
      out.write("		  } else {\n");
      out.write("				  setCookie(\"credentials\",\"\");\n");
      out.write("		  }\n");
      out.write("		  return true;	\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("		function loadUser() {\n");
      out.write("			var credentials = $.cookies.get(\"credentials\");\n");
      out.write("			if(credentials) {\n");
      out.write("				document.login.j_username.value = credentials['username'];\n");
      out.write("				document.login.j_password.value = credentials['password'];\n");
      out.write("				document.login.remember_me.checked = credentials['remember'];\n");
      out.write("				document.login.login_button.focus();\n");
      out.write("			} else {\n");
      out.write("				document.login.j_username.focus();\n");
      out.write("			}\n");
      out.write("		}\n");
      out.write("		\n");
      out.write("	</script>\n");
      out.write("	\n");
      out.write("</head>\n");
      out.write("<body class=\"ui-widget-content\" style=\"border:none;\" onload=\"loadUser();\">\n");
      out.write("<section>\n");
      out.write("	<form name=\"login\" id=\"login\" action=\"j_security_check\" method=\"POST\" onsubmit=\"return validateForm(this);\">\n");
      out.write("		<fieldset>\n");
      out.write("			<legend><font>Login</font></legend>\n");
      out.write("			<h1><script>document.write(languages['PageTitle']) </script> 2</h1> <h4><script>document.write(languages['Workstation']) </script> -\n");
      out.write("						<script>document.write(languages['Version']);</script>\n");
      out.write("						<script> document.write(languages['VersionNo']); </script></h4>\n");
      out.write("			\n");
      out.write("			<label><font><script>document.write(languages['UserName'])</script> </font><span class=\"mandatory\"><font>*</font></span><font> </font></label>\n");
      out.write("			<input type=\"text\" name=\"j_username\" class=\"textInput\" placeholder=\"Username\" required>\n");
      out.write("\n");
      out.write("			<label><font><script>document.write(languages['Password'])</script> </font><span class=\"mandatory\"><font>*</font></span><font> </font></label>\n");
      out.write("			<input type=\"password\" name=\"j_password\" class=\"textInput\" placeholder=\"Password\" required>\n");
      out.write("\n");
      out.write("			<table> <tr> <td> <input type=\"checkbox\" name=\"remember_me\" value=\"Remember Me\"/> </td> \n");
      out.write("			<td style=\"font-size: 10pt;\"><script>document.write(languages['RememberMe'])</script> </td> </tr> </table> </td>			\n");
      out.write("			\n");
      out.write("			<input type=\"submit\" name=\"submit\" id=\"loginButton\" value=\"\" class=\"button disabled\">\n");
      out.write("		</fieldset>\n");
      out.write("	</form>\n");
      out.write("</section>\n");
      out.write("<!--     <footer align=\"center\"><script>document.write(languages['Footer'])</script></footer> -->\n");
      out.write("<!-- 	<div style=\"text-align: center; margin-top: 10px; font-size: 10px;\">This version of oviyam, being a free open-source software is not intended for diagnosis</div> -->\n");
      out.write("<div style=\"text-align: center; margin-top: 3%; font-size: 60%;\"><script>document.write(languages['disclaimer'])</script> <br> <br> <script>document.write(languages['limitation'])</script></div>\n");
      out.write("\n");
      out.write("<div style=\"width: 100%; position: absolute; bottom: 0px;\">\n");
      out.write("<table style=\"width:100%\">\n");
      out.write("<tr>\n");
      out.write("<td><a href=\"http://dcm4che.org\" target=\"_blank\"><img src=\"images/dcm4che.png\" alt=\"dcm4che.org\" style=\"width: 132px;\" /></a></td> \n");
      out.write("<td style=\"text-align: center\"><img src=\"images/html5.png\" alt=\"\" style=\"width: 132px\" /> </td>\n");
      out.write("<td style=\"text-align: right\"><a href=\"http://oviyam.raster.in\" target=\"_blank\"><img src=\"images/raster.png\" alt=\"Raster Images\" style=\"width: 132px\" /></a></td>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
