/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-01-10 18:26:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class queryResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1614217482000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/oviyam2/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1064359020000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/oviyam2/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064359020000L));
    _jspx_dependants.put("/WEB-INF/tlds/PatientInfo.tld", Long.valueOf(1614217482000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/oviyam2/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1064359020000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("/* ***** BEGIN LICENSE BLOCK *****\n");
      out.write("* Version: MPL 1.1/GPL 2.0/LGPL 2.1\n");
      out.write("*\n");
      out.write("* The contents of this file are subject to the Mozilla Public License Version\n");
      out.write("* 1.1 (the \"License\"); you may not use this file except in compliance with\n");
      out.write("* the License. You may obtain a copy of the License at\n");
      out.write("* http://www.mozilla.org/MPL/\n");
      out.write("*\n");
      out.write("* Software distributed under the License is distributed on an \"AS IS\" basis,\n");
      out.write("* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License\n");
      out.write("* for the specific language governing rights and limitations under the\n");
      out.write("* License.\n");
      out.write("*\n");
      out.write("* The Original Code is part of Oviyam, an web viewer for DICOM(TM) images\n");
      out.write("* hosted at http://skshospital.net/pacs/webviewer/oviyam_0.6-src.zip\n");
      out.write("*\n");
      out.write("* The Initial Developer of the Original Code is\n");
      out.write("* Raster Images\n");
      out.write("* Portions created by the Initial Developer are Copyright (C) 2014\n");
      out.write("* the Initial Developer. All Rights Reserved.\n");
      out.write("*\n");
      out.write("* Contributor(s):\n");
      out.write("* Babu Hussain A\n");
      out.write("* Balamurugan R\n");
      out.write("* Devishree V\n");
      out.write("* Guruprasath R\n");
      out.write("* Karthikeyan S\n");
      out.write("* Meer Asgar Hussain B\n");
      out.write("* Prakash J\n");
      out.write("* Suresh V\n");
      out.write("* Yogapraveen K\n");
      out.write("*\n");
      out.write("* Alternatively, the contents of this file may be used under the terms of\n");
      out.write("* either the GNU General Public License Version 2 or later (the \"GPL\"), or\n");
      out.write("* the GNU Lesser General Public License Version 2.1 or later (the \"LGPL\"),\n");
      out.write("* in which case the provisions of the GPL or the LGPL are applicable instead\n");
      out.write("* of those above. If you wish to allow use of your version of this file only\n");
      out.write("* under the terms of either the GPL or the LGPL, and not to allow others to\n");
      out.write("* use your version of this file under the terms of the MPL, indicate your\n");
      out.write("* decision by deleting the provisions above and replace them with the notice\n");
      out.write("* and other provisions required by the GPL or the LGPL. If you do not delete\n");
      out.write("* the provisions above, a recipient may use your version of this file under\n");
      out.write("* the terms of any one of the MPL, the GPL or the LGPL.\n");
      out.write("*\n");
      out.write("* ***** END LICENSE BLOCK ***** */\n");
      out.write("-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String patName = request.getParameter("patientName");
	String tabName = request.getParameter("tabName");

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_fmt_005fsetBundle_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write("/* \n");
      out.write("##Device = Desktops\n");
      out.write("##Screen = 1281px to higher resolution desktops\n");
      out.write("*/\n");
      out.write("@media ( min-width : 1281px) {\n");
      out.write("	.dataTables_scrollBody {\n");
      out.write("		max-height: 100% !important;\n");
      out.write("		overflow: auto;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* \n");
      out.write("##Device = Laptops, Desktops\n");
      out.write("##Screen = B/w 1025px to 1280px\n");
      out.write("*/\n");
      out.write("@media ( min-width : 1025px) and (max-width: 1280px) {\n");
      out.write("	.dataTables_scrollBody {\n");
      out.write("		max-height: 100% !important;\n");
      out.write("		overflow: auto;\n");
      out.write("	}\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* \n");
      out.write("##Device = Tablets, Ipads (portrait)\n");
      out.write("##Screen = B/w 768px to 1024px\n");
      out.write("*/\n");
      out.write("@media ( min-width : 768px) and (max-width: 1024px) {\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* \n");
      out.write("##Device = Tablets, Ipads (landscape)\n");
      out.write("##Screen = B/w 768px to 1024px\n");
      out.write("*/\n");
      out.write("@media ( min-width : 768px) and (max-width: 1024px) and (orientation:\n");
      out.write("	landscape) {\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dataTables_scrollBody {\n");
      out.write("	min-height: 80% !important;\n");
      out.write("	max-height: 88% !important;\n");
      out.write("	border-collapse: collapse;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dataTables_wrapper {\n");
      out.write("	border-collapse: collapse;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dataTables_info {\n");
      out.write("	width: auto;\n");
      out.write("	font-size: 13px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dataTables_length {\n");
      out.write("	font-size: 14px;\n");
      out.write("	margin-bottom: -21px;\n");
      out.write("	margin-left: 54px;\n");
      out.write("	position: absolute;\n");
      out.write("	text-align: justify;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dataTables_paginate .ui-button {\n");
      out.write("	/* margin-right: 4px !important; */\n");
      out.write("	margin: 3px !important;\n");
      out.write("	font-size: 14px;\n");
      out.write("	padding: 3px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".display td {\n");
      out.write("	/* text-align: left; */\n");
      out.write("	padding: 15px !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".display {\n");
      out.write("	border-collapse: collapse !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write("tr.odd {\n");
      out.write("	background-color: #e6e6e6;\n");
      out.write("}\n");
      out.write("\n");
      out.write("tr.even {\n");
      out.write("	background-color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table.display tr.even.row_selected td {\n");
      out.write("	background-color: #718ea0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table.display tr.odd.row_selected td {\n");
      out.write("	background-color: #718ea0;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table.display tr:hover td {\n");
      out.write("	background: rgba(24, 143, 255, 0.16) !important;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table.display tr.even.row_selected:hover td,\n");
      out.write("table.display tr.odd.row_selected:hover td {\n");
      out.write("	background-color: #718ea0 !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/*\n");
      out.write("* Sorting classes for columns\n");
      out.write("*/\n");
      out.write("\n");
      out.write("/* For the standard odd/even */\n");
      out.write("tr.odd td.sorting_1 {\n");
      out.write("	background-color: #e6e6e6;\n");
      out.write("}\n");
      out.write("\n");
      out.write("tr.even td.sorting_1 {\n");
      out.write("	background-color: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".display, .dataTables_scrollHeadInner {\n");
      out.write("	width: 100% !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dataTables_scrollHeadInner {\n");
      out.write("	width: 100% !important;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dataTables_filter {\n");
      out.write("	font-size: 14px;\n");
      out.write("}\n");
      out.write(".dataTables_scrollHead table thead{\n");
      out.write("	display:none;\n");
      out.write("}\n");
      out.write(".instance-legend{\n");
      out.write("	position: absolute;\n");
      out.write("    margin-top: -28px;\n");
      out.write("	right: 400px;\n");
      out.write("}\n");
      out.write(".instance-legend ul li{\n");
      out.write("	display: inline-flex;\n");
      out.write("    vertical-align: middle;\n");
      out.write("    line-height: 16px;\n");
      out.write("	margin-right: 10px;\n");
      out.write("    font-size: 13px;\n");
      out.write("    color: #fff;\n");
      out.write("}\n");
      out.write(".instance-legend ul li:first-child span{\n");
      out.write("	display: inline-block;\n");
      out.write("	background-color: #6fbb6f;\n");
      out.write("	width: 15px;\n");
      out.write("	height: 15px;\n");
      out.write("	margin-right: 5px;\n");
      out.write("}\n");
      out.write(".instance-legend ul li:last-child span{\n");
      out.write("	display: inline-block;\n");
      out.write("	background-color: #FF8A00;\n");
      out.write("	width: 15px;\n");
      out.write("	height: 15px;\n");
      out.write("	margin-right: 5px;\n");
      out.write("}\n");
      out.write("table.display td:first-child{\n");
      out.write("	width: 5%;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(2){\n");
      out.write("	width: 20%;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(3){\n");
      out.write("	width: 14%;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(4){\n");
      out.write("	width: 7%;\n");
      out.write("	padding: 20px !important;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(5){\n");
      out.write("	width: 20%;\n");
      out.write("    padding: 0!important;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(6){\n");
      out.write("	width: 20%;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(7){\n");
      out.write("	width: 20%;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(8){\n");
      out.write("	width: 20%;\n");
      out.write("}\n");
      out.write("table.display td:nth-of-type(9){\n");
      out.write("	width: 20%;\n");
      out.write("}\n");
      out.write("table.display thead th{\n");
      out.write("	text-align: left;\n");
      out.write("	position: sticky;\n");
      out.write("    top: 0;\n");
      out.write("}\n");
      out.write("/* table.display th:first-child{\n");
      out.write("	width: 5%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(2){\n");
      out.write("	width: 20%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(3){\n");
      out.write("	width: 20%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(4){\n");
      out.write("	width: 20%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(5){\n");
      out.write("	width: 20%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(6){\n");
      out.write("	width: 20%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(7){\n");
      out.write("	width: 20%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(8){\n");
      out.write("	width: 20%!important;\n");
      out.write("}\n");
      out.write("table.display th:nth-of-type(9){\n");
      out.write("	width: 20%!important;\n");
      out.write("} */\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\" src=\"js/LoadLanguage.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	var dTable;\n");
      out.write("	$(document).ready(function () {\n");
      out.write("	var tableName = '#");
      out.print(tabName);
      out.write("_table';\n");
      out.write("	var searchPane = '#");
      out.print(tabName);
      out.write("_search';\n");
      out.write("	$(searchPane).show();\n");
      out.write("	\n");
      out.write("	dTable = $(tableName).DataTable({\n");
      out.write("			\"bJQueryUI\": true,\n");
      out.write("			//\"sPaginationType\": \"full_numbers\",											\n");
      out.write("			\"bPaginate\": true,\n");
      out.write("			\"responsive\": true,\n");
      out.write("			//\"bFilter\": false,\n");
      out.write("			\"oLanguage\": {\n");
      out.write("				\"sSearch\": languages.Filter,\n");
      out.write("				\"sLengthMenu\": languages.LengthMenu,\n");
      out.write("				\"sZeroRecords\": languages.ZeroRecords,\n");
      out.write("				\"sInfo\": languages.Info,\n");
      out.write("				\"sInfoEmpty\": languages.InfoEmpty,\n");
      out.write("				\"sInfoFiltered\": languages.InfoFiltered\n");
      out.write("			},\n");
      out.write("			\"sScrollY\": \"87%\",\n");
      out.write("			\"bScrollCollapse\": true,\n");
      out.write("			\"bAutoWidth\": true,\n");
      out.write("			\"sScrollX\": \"100%\",\n");
      out.write("			\"sScrollBody\":\"100%\",\n");
      out.write("			//\"sScrollXInner\": \"100%\",\n");
      out.write("			\"aaSorting\": [[4, \"desc\"]],\n");
      out.write("			\"pageLength\":25,\n");
      out.write("			\"aoColumnDefs\": [{\n");
      out.write("					 \"aTargets\": [0],\n");
      out.write("					 \"fnCreatedCell\": function (nTd, sData, oData, iRow, iCol) {\n");
      out.write("							if (sData.indexOf('img') >= 0) {\n");
      out.write("									$(nTd).css('padding', '0px');\n");
      out.write("									$(nTd).css('text-align', 'center');\n");
      out.write("							}\n");
      out.write("							\n");
      out.write("					  }\n");
      out.write("			}],\n");
      out.write("			\"aoColumns\": [null, null, null, null, null, null, null, null, null, { \"bVisible\": false }, { \"bVisible\": false }],\n");
      out.write("			\"fnDrawCallback\": function(oSettings) {\n");
      out.write("	        	highlightModalities();\n");
      out.write("	        	instanceAvailability();\n");
      out.write("	        }\n");
      out.write("	});\n");
      out.write("\n");
      out.write("	function highlightModalities() {\n");
      out.write("        $('[class^=\"CT\"]').css(\"background\", \"#8D661F\");\n");
      out.write("        $('[class^=\"CR\"]').css(\"background\", \"#008080\");\n");
      out.write("        $('[class^=\"MR\"]').css(\"background\", \"#4F8F78\");\n");
      out.write("        $('[class^=\"DX\"]').css(\"background\", \"#092B5A\");\n");
      out.write("        $('[class^=\"XA\"]').css(\"background\", \"#BEB072\");\n");
      out.write("        $('[class^=\"PX\"]').css(\"background\", \"#FF6347\");\n");
      out.write("        $('[class^=\"SC\"]').css(\"background\", \"#6E5F5F\");\n");
      out.write("        $('[class^=\"OT\"]').css(\"background\", \"#587BAC\");\n");
      out.write("        $('[class^=\"XC\"]').css(\"background\", \"#FF6347\");\n");
      out.write("        $('[class^=\"SR\"]').css(\"background\", \"#6E5F5F\");\n");
      out.write("        $('[class^=\"US\"]').css(\"background\", \"#676F73\");\n");
      out.write("        $('[class^=\"ES\"]').css(\"background\", \"#15607C\");\n");
      out.write("        $('[class^=\"ECG\"]').css(\"background\", \"#736767\");\n");
      out.write("        $('[class^=\"PR\"]').css(\"background\", \"#008080\");\n");
      out.write("    }\n");
      out.write("	\n");
      out.write("	function instanceAvailability() {\n");
      out.write("		 $('[class^=\"ONLINE\"]').css(\"background\", \"#6fbb6f\");\n");
      out.write("		 $('[class^=\"NEARLINE\"]').css(\"background\", \"#FF8A00\");\n");
      out.write("		 $('[class^=\"OFFLINE\"]').css(\"background\", \"#948a8a\");\n");
      out.write("		 $('[class^=\"UNAVAILABLE\"]').css(\"background\", \"#ef0f0f\");\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	$.fn.dataTableInstances[");
      out.print(request.getParameter("tabIndex"));
      out.write("] = dTable;\n");
      out.write("\n");
      out.write("	if (");
      out.print(request.getParameter("search"));
      out.write("!=null && !");
      out.print(request.getParameter("search"));
      out.write(") { //For Direct launch\n");
      out.write("			$('#searchToggler').hide();\n");
      out.write("			$('#Toggler').css('top', '0.5%');\n");
      out.write("	}                 \n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$('.fg-toolbar').click(function () {\n");
      out.write("		$('.dataTables_scrollBody table thead').hide();\n");
      out.write("		$('.dataTables_scrollHead table thead').show();\n");
      out.write("	});\n");
      out.write("	\n");
      out.write("	$('.dataTables_scrollBody table thead').click(function () {\n");
      out.write("		$('.dataTables_scrollBody table thead').hide();\n");
      out.write("		$('.dataTables_scrollHead table thead').show();\n");
      out.write("	});\n");
      out.write("\n");
      out.write("	function toggleDivider(divider) {\n");
      out.write("		var serverName = $(\"#tabUL .ui-state-active\").find('a').get(0);\n");
      out.write("		serverName = $(serverName).attr('href');\n");
      out.write("		$('.dataTables_scrollBody table thead').show();\n");
      out.write("		$('.dataTables_scrollHead table thead').hide();\n");
      out.write("\n");
      out.write("		var toggler = $(serverName + '_Toggler');\n");
      out.write("		var westPane = $(serverName + '_westPane');\n");
      out.write("		var searchPane = $(serverName + '_search');\n");
      out.write("\n");
      out.write("			if ($(westPane).is(\":visible\")) {\n");
      out.write("					// $(westPane).html('');\n");
      out.write("					$(westPane).hide();\n");
      out.write("					console.log($(toggler).next());\n");
      out.write("					console.log($(toggler).next());\n");
      out.write("					$(toggler).next().css('width', '100%');\n");
      out.write("					$(toggler).next().css('left', '0px');\n");
      out.write("					$(toggler).css('left', '0px');\n");
      out.write("					$(divider).attr('title', 'Show Preview');\n");
      out.write("					if ($(searchPane).is(\":visible\")) {\n");
      out.write("							$(divider).css('background', 'url(\"images/showall.png\")');\n");
      out.write("							$(divider).next().css('background', 'url(\"images/hideall.png\")');\n");
      out.write("					} else {\n");
      out.write("							$(divider).css('background', 'url(\"images/hidesearch.png\")');\n");
      out.write("							$(divider).next().css('background', 'url(\"images/hidewest.png\")');\n");
      out.write("					}\n");
      out.write("			} else {\n");
      out.write("\n");
      out.write("					loadWest();\n");
      out.write("					$(westPane).show();\n");
      out.write("					$(toggler).next().css('left', '256px');\n");
      out.write("					$(toggler).next().css('width', $('body').width() - 260 + 'px');\n");
      out.write("					$(divider).attr('title', 'Hide Preview');\n");
      out.write("					$(toggler).css('left', '256px');\n");
      out.write("					if ($(searchPane).is(\":visible\")) {\n");
      out.write("							$(divider).css('background', 'url(\"images/hidewest.png\")');\n");
      out.write("							$(divider).next().css('background', 'url(\"images/hidesearch.png\")');\n");
      out.write("					} else {\n");
      out.write("							$(divider).css('background', 'url(\"images/hideall.png\")');\n");
      out.write("							$(divider).next().css('background', 'url(\"images/showall.png\")');\n");
      out.write("					}\n");
      out.write("			}\n");
      out.write("			$('#' + tableName + '_table').css('width', '100%');			\n");
      out.write("			dTable.columns.adjust().draw();\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function toggleSearch(divider) {\n");
      out.write("		$('.dataTables_scrollBody table thead').hide();\n");
      out.write("		$('.dataTables_scrollHead table thead').show();\n");
      out.write("		var serverName = $(\"#tabUL .ui-state-active\").find('a').get(0);\n");
      out.write("		serverName = $(serverName).attr('href');\n");
      out.write("		var westPane = $(serverName + '_westPane');\n");
      out.write("		var searchPane = $(serverName + '_search');\n");
      out.write("		var tabContent = $(serverName + '_content');\n");
      out.write("		var toggler = $(serverName + '_Toggler');\n");
      out.write("\n");
      out.write("			if ($(searchPane).is(\":visible\")) {\n");
      out.write("					$(searchPane).hide();\n");
      out.write("					// $(tabContent).css('height', '100%');\n");
      out.write("					$(tabContent).css('height', '83%');\n");
      out.write("					$(toggler).css('top', '1%');\n");
      out.write("					$(toggler).next().css('top', '0px');\n");
      out.write("					// $('#Toggler').next().css('height', '100%');\n");
      out.write("					$(toggler).next().css('height', '83%');\n");
      out.write("					$(divider).attr('title', 'Show Search');\n");
      out.write("\n");
      out.write("					if ($(westPane).is(\":visible\")) {\n");
      out.write("							$(divider).css('background', 'url(\"images/showall.png\")');\n");
      out.write("							$(divider).prev().css('background', 'url(\"images/hideall.png\")');\n");
      out.write("					} else {\n");
      out.write("							$(divider).css('background', 'url(\"images/hidewest.png\")');\n");
      out.write("							$(divider).prev().css('background', 'url(\"images/hidesearch.png\")');\n");
      out.write("					}\n");
      out.write("			} else {\n");
      out.write("					$(searchPane).show();\n");
      out.write("					$(divider).attr('title', 'Hide Search');\n");
      out.write("					$(tabContent).css('height', '83%');\n");
      out.write("					$(toggler).css('top', '13.5%');\n");
      out.write("					$(toggler).next().css('top', '13%');\n");
      out.write("					$(toggler).next().css('height', '83%');\n");
      out.write("\n");
      out.write("					if ($(westPane).is(\":visible\")) {\n");
      out.write("							$(divider).css('background', 'url(\"images/hidesearch.png\")');\n");
      out.write("							$(divider).prev().css('background','url(\"images/hidewest.png\")');\n");
      out.write("					} else {\n");
      out.write("							$(divider).css('background', 'url(\"images/hideall.png\")');\n");
      out.write("							$(divider).prev()\n");
      out.write("							.css('background', 'url(\"images/showall.png\")');\n");
      out.write("					}\n");
      out.write("			}\n");
      out.write("	}\n");
      out.write("\n");
      out.write("	function loadWest() {\n");
      out.write("		var selected = dTable.$('tr.row_selected');\n");
      out.write("\n");
      out.write("		if (selected.length > 0) {\n");
      out.write("			// 		        	var iPos = dTable.fnGetData($(dTable.find('.row_selected')).get(0));\n");
      out.write("			var iPos = dTable.row(this).data();\n");
      out.write("			if (iPos == null) {\n");
      out.write("				return;\n");
      out.write("			}\n");
      out.write("			showWestPane(iPos);\n");
      out.write("		}\n");
      out.write("	}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("	");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\n');
            out.write('	');
            out.write('	');
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /queryResult.jsp(489,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.preview=='true'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("			<div id=\"");
                  out.print(tabName);
                  out.write("_westPane\"\n");
                  out.write("				style=\"width: 255px; visibility: visible; display: block; z-index: 0; float: left; height: 94%;\"></div>\n");
                  out.write("\n");
                  out.write("			<div id=\"");
                  out.print(tabName);
                  out.write("_Toggler\"\n");
                  out.write("				style=\"position: absolute; top: 13.5%; left: 256px; z-index: 3;\">\n");
                  out.write("\n");
                  out.write("				<div id=\"");
                  out.print(tabName);
                  out.write("_westToggler\" name=\"testToggler\" title=\"Hide Preview\"\n");
                  out.write("					class=\"ui-state-default\"\n");
                  out.write("					onmouseover=\"this.className='ui-state-hover'\"\n");
                  out.write("					onmouseout=\"this.className='ui-state-default'\"\n");
                  out.write("					style=\"width: 24px; height: 24px; cursor: pointer; float: left; z-index: 3; background: url('images/hidewest.png'); border: none;\"\n");
                  out.write("					onclick=\"this.className='ui-state-default';toggleDivider(this);\"></div>\n");
                  out.write("\n");
                  out.write("				<div id=\"");
                  out.print(tabName);
                  out.write("_searchToggler\" title=\"Hide Search\"\n");
                  out.write("					class=\"ui-state-default toggler\"\n");
                  out.write("					onmouseover=\"this.className='ui-state-hover'\"\n");
                  out.write("					onmouseout=\"this.className='ui-state-default'\"\n");
                  out.write("					style=\"width: 24px; height: 24px; cursor: pointer; float: left; z-index: 3; background: url('images/hidesearch.png'); border: none;\"\n");
                  out.write("					onclick=\"this.className='ui-state-default'; toggleSearch(this);\"></div>\n");
                  out.write("			</div>\n");
                  out.write("\n");
                  out.write("			");
                  if (_jspx_meth_c_005fchoose_005f1(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("\n");
                  out.write("		");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\n");
            out.write("\n");
            out.write("		");
            if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
              return;
            out.write('\n');
            out.write('	');
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\n");
      out.write("\n");
      out.write("	<table class=\"display\" id=\"");
      out.print(tabName);
      out.write("_table\" style=\"font-size: 14px;\">\n");
      out.write("\n");
      out.write("		<thead>\n");
      out.write("			<tr>\n");
      out.write("				<th></th>\n");
      out.write("				<th class='patientId'></th>\n");
      out.write("				<th class='patientName'></th>\n");
      out.write("				<th class=\"gender\"></th>\n");
      out.write("				<!--<th>");
      if (_jspx_meth_fmt_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</th>\n");
      out.write("					<th>");
      if (_jspx_meth_fmt_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("</th>-->\n");
      out.write("				<th class='studyDate'></th>\n");
      out.write("				<th class='studyDescp'></th>\n");
      out.write("				<th class=\"lblReferPhysician\"></th>\n");
      out.write("				<th class='lblModality'></th>\n");
      out.write("				<th class='instanceCnt'></th>\n");
      out.write("				<th>Study Instance UID</th>\n");
      out.write("				<th>Series Count</th>\n");
      out.write("			</tr>\n");
      out.write("		</thead>\n");
      out.write("		<tbody>\n");
      out.write("			");
      //  pat:Patient
      in.raster.oviyam.handler.PatientInfoHandler _jspx_th_pat_005fPatient_005f0 = new in.raster.oviyam.handler.PatientInfoHandler();
      _jsp_getInstanceManager().newInstance(_jspx_th_pat_005fPatient_005f0);
      try {
        _jspx_th_pat_005fPatient_005f0.setJspContext(_jspx_page_context);
        // /queryResult.jsp(551,3) name = patientId type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setPatientId((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.patientId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = patientName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setPatientName(patName);
        // /queryResult.jsp(551,3) name = birthDate type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setBirthDate((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.birthDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = modality type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setModality((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.modality}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = from type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setFrom((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.from}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = to type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setTo((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.to}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = searchDays type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setSearchDays((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.searchDays}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = accessionNumber type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setAccessionNumber((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.accessionNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = referPhysician type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setReferPhysician((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.referPhysician}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = studyDescription type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setStudyDescription((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.studyDesc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = dcmURL type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setDcmURL((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.dcmURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = fromTime type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setFromTime((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.fromTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = toTime type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setToTime((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.toTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /queryResult.jsp(551,3) name = serverURL type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_pat_005fPatient_005f0.setServerURL((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.serverURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        _jspx_th_pat_005fPatient_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_pat_005fPatient_005f0, null));
        _jspx_th_pat_005fPatient_005f0.doTag();
      } finally {
        _jsp_getInstanceManager().destroyInstance(_jspx_th_pat_005fPatient_005f0);
      }
      out.write("\n");
      out.write("		</tbody>\n");
      out.write("	</table>\n");
      out.write("	<div class=\"instance-legend\">\n");
      out.write("		<ul>\n");
      out.write("			<li><span></span> Online</li>\n");
      out.write("			<li><span></span> Nearline</li>\n");
      out.write("		</ul>\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fsetBundle_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:setBundle
    org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag _jspx_th_fmt_005fsetBundle_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag) _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetBundleTag.class);
    boolean _jspx_th_fmt_005fsetBundle_005f0_reused = false;
    try {
      _jspx_th_fmt_005fsetBundle_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fsetBundle_005f0.setParent(null);
      // /queryResult.jsp(63,0) name = basename type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fsetBundle_005f0.setBasename("resources.i18n.Messages");
      // /queryResult.jsp(63,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fsetBundle_005f0.setVar("lang");
      int _jspx_eval_fmt_005fsetBundle_005f0 = _jspx_th_fmt_005fsetBundle_005f0.doStartTag();
      if (_jspx_th_fmt_005fsetBundle_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fsetBundle_0026_005fvar_005fbasename_005fnobody.reuse(_jspx_th_fmt_005fsetBundle_005f0);
      _jspx_th_fmt_005fsetBundle_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fsetBundle_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fsetBundle_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\n");
          out.write("				");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\n");
          out.write("			");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /queryResult.jsp(512,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.search=='true'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div\n");
          out.write("						style=\"float: left; height: 84%; position: absolute; top: 13%; left: 257px; right: 0px; bottom: 0px; padding: 0px'\">\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("					<div\n");
          out.write("						style=\"float: left; height: 100%; position: absolute; top: 0px; left: 257px; right: 0px; bottom: 0px; padding: 0px'\">\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("			<div style=\"float: left; width: 100%; padding: 0px'\">\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f0_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f0.setParent(null);
      // /queryResult.jsp(539,12) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setKey("dateOfBirth");
      // /queryResult.jsp(539,12) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f0.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lang}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      _jspx_th_fmt_005fmessage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    boolean _jspx_th_fmt_005fmessage_005f1_reused = false;
    try {
      _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fmessage_005f1.setParent(null);
      // /queryResult.jsp(540,9) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f1.setKey("accessionNumber");
      // /queryResult.jsp(540,9) name = bundle type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fmessage_005f1.setBundle((javax.servlet.jsp.jstl.fmt.LocalizationContext) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${lang}", javax.servlet.jsp.jstl.fmt.LocalizationContext.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
      if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fbundle_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      _jspx_th_fmt_005fmessage_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fmessage_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fmessage_005f1_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public void invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<td><img src=\"images/details_open.png\" alt=\"\" /> <img\n");
      out.write("						src=\"images/green.png\" style=\"display: none;\" id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyIUID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\n");
      out.write("						alt=\"\" /></td>\n");
      out.write("					<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patientId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patientName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patientGender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<!--<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${birthDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("						<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${accessionNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>-->\n");
      out.write("					<td data-order=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dateOrder}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyDescription}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${referPhysician}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<td align=\"center\">    \n");
      out.write("						<div class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modality}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"color: #fff; font-weight: bold; display:inline; padding: 6px; text-align: center; background: #008080; border-radius: 0px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modality}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("                    </td>\n");
      out.write("					<td>\n");
      out.write("						<div class=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${instanceAvailability}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${instanceAvailability}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" \n");
      out.write("							style=\"color: #fff; font-weight: bold; \n");
      out.write("									display:inline-block; padding: 6px; \n");
      out.write("									text-align: center; border-radius: 0px;min-width: 30px;\">\n");
      out.write("										");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalInstances}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</td>\n");
      out.write("					<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyIUID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalSeries}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("					<!-- <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patientGender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td> -->\n");
      out.write("				</tr>\n");
      out.write("			");
      return;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
