/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2022-01-06 09:18:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;
import java.net.URLEncoder;

public final class westContainer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/tlds/SeriesDetails.tld", Long.valueOf(1614217482000L));
    _jspx_dependants.put("/WEB-INF/tlds/ImageInfo.tld", Long.valueOf(1614217482000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1614217482000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/oviyam2/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1064359020000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/oviyam2/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064359020000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.5/webapps/oviyam2/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1064359020000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.net.URLDecoder");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"ErrorPage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\n");
      out.write("/* ***** BEGIN LICENSE BLOCK *****\n");
      out.write("* Version: MPL 1.1/GPL 2.0/LGPL 2.1\n");
      out.write("*\n");
      out.write("* The contents of this file are subject to the Mozilla Public License Version\n");
      out.write("* 1.1 (the \"License\"); you may not use this file except in compliance with\n");
      out.write("* the License. You may obtain a copy of the License at\n");
      out.write("* http://www.mozilla.org/MPL/\n");
      out.write("*\n");
      out.write("* Software distributed under the License is distributed on an \"AS IS\" basis,\n");
      out.write("* WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License\n");
      out.write("* for the specific language governing rights and limitations under the\n");
      out.write("* License.\n");
      out.write("*\n");
      out.write("* The Original Code is part of Oviyam, an web viewer for DICOM(TM) images\n");
      out.write("* hosted at http://skshospital.net/pacs/webviewer/oviyam_0.6-src.zip\n");
      out.write("*\n");
      out.write("* The Initial Developer of the Original Code is\n");
      out.write("* Raster Images\n");
      out.write("* Portions created by the Initial Developer are Copyright (C) 2014\n");
      out.write("* the Initial Developer. All Rights Reserved.\n");
      out.write("*\n");
      out.write("* Contributor(s):\n");
      out.write("* Babu Hussain A\n");
      out.write("* Balamurugan R\n");
      out.write("* Devishree V\n");
      out.write("* Karthikeyan S\n");
      out.write("* Meer Asgar Hussain B\n");
      out.write("* Prakash J\n");
      out.write("* Suresh V\n");
      out.write("*\n");
      out.write("* Alternatively, the contents of this file may be used under the terms of\n");
      out.write("* either the GNU General Public License Version 2 or later (the \"GPL\"), or\n");
      out.write("* the GNU Lesser General Public License Version 2.1 or later (the \"LGPL\"),\n");
      out.write("* in which case the provisions of the GPL or the LGPL are applicable instead\n");
      out.write("* of those above. If you wish to allow use of your version of this file only\n");
      out.write("* under the terms of either the GPL or the LGPL, and not to allow others to\n");
      out.write("* use your version of this file under the terms of the MPL, indicate your\n");
      out.write("* decision by deleting the provisions above and replace them with the notice\n");
      out.write("* and other provisions required by the GPL or the LGPL. If you do not delete\n");
      out.write("* the provisions above, a recipient may use your version of this file under\n");
      out.write("* the terms of any one of the MPL, the GPL or the LGPL.\n");
      out.write("*\n");
      out.write("* ***** END LICENSE BLOCK ***** */\n");
      out.write("-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String patient = request.getParameter("patient");
	String patName = request.getParameter("patientName");
	String studyDesc = request.getParameter("studyDesc");
	String encodedPatient = URLEncoder.encode( patient, "UTF-8" );
	patient = URLDecoder.decode(patient,"UTF-8");
    patName = URLDecoder.decode(patName,"UTF-8");
    studyDesc = URLDecoder.decode(studyDesc,"UTF-8");

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("	<head>\n");
      out.write("	\n");
      out.write("		<style type=\"text/css\">\n");
      out.write("			.heading\n");
      out.write("            {\n");
      out.write("                font-family: Arial;\n");
      out.write("                font-size: 20px;\n");
      out.write("                font-weight: bold;\n");
      out.write("                padding-left: 3px;\n");
      out.write("                width: 100%;\n");
      out.write("                white-space: nowrap;\n");
      out.write("                text-overflow: ellipsis;\n");
      out.write("                overflow: hidden;\n");
      out.write("            }\n");
      out.write("			\n");
      out.write("			.seriesTable {\n");
      out.write("				table-layout: fixed;\n");
      out.write("				width: 100%;\n");
      out.write("				font-family: Arial;\n");
      out.write("				font-size: 12px;\n");
      out.write("				border-spacing: 0px;\n");
      out.write("				padding-left: 2px;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.scale-image {\n");
      out.write("				width: 30%;\n");
      out.write("				height: 30%;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.accordion {\n");
      out.write("				padding:5px;\n");
      out.write("				font-weight:bold;\n");
      out.write("				cursor:pointer;\n");
      out.write("				background-color:#666;				\n");
      out.write("				background-position:right center;\n");
      out.write("				background-repeat:no-repeat; color:#F90;\n");
      out.write("				border:1px solid #333;\n");
      out.write("				font-size: 14px;\n");
      out.write("				font-family: Arial;\n");
      out.write("				position: relative;\n");
      out.write("			}	\n");
      out.write("			.accordion:hover {\n");
      out.write("				background-color:#555;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.loading {\n");
      out.write("				background-image:url(images/loading.gif);\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			#otherStudiesInfo {\n");
      out.write("				padding:5px;\n");
      out.write("				font-weight:bold;\n");
      out.write("				cursor:pointer;\n");
      out.write("				background-color:#222;	\n");
      out.write("				color: #fff;\n");
      out.write("				font-family: Arial;\n");
      out.write("				font-size: 14px; \n");
      out.write("				text-align: center; \n");
      out.write("				margin: 7px 0px 7px 0;			\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.open {\n");
      out.write("				background-image:url(images/arrow_up.gif);\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.close {\n");
      out.write("				background-image:url(images/arrow_down.gif);\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			::-webkit-scrollbar {\n");
      out.write("				width: 14px;\n");
      out.write("				background: #464646;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("            ::-webkit-scrollbar-track {\n");
      out.write("			    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);\n");
      out.write("			}   \n");
      out.write("			\n");
      out.write("			::-webkit-scrollbar-thumb {\n");
      out.write(" 			    -webkit-border-radius: 10px; \n");
      out.write(" 			    border-radius: 10px;\n");
      out.write("				background: #262626;\n");
      out.write("			    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5); \n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.otherStudies-min {\n");
      out.write("				overflow:auto;\n");
      out.write("				height: auto;\n");
      out.write("				width: 100%;\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			.otherStudies-exp {\n");
      out.write("				overflow:auto;\n");
      out.write("				max-height: 75%;\n");
      out.write("				width: 100%;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.otherModalities {\n");
      out.write("				padding: 5px;\n");
      out.write("				margin: 5px;\n");
      out.write("				border-radius: 6px;\n");
      out.write("				background-color: #585858;\n");
      out.write("				outline: none;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.selectedModality {\n");
      out.write("				color: #FF8A00;\n");
      out.write("				font-weight: bolder;\n");
      out.write("				border: 1px solid #FF8A00;\n");
      out.write("				outline: none;\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("			.unselectedModality {\n");
      out.write("				border: 1px solid #000;\n");
      out.write("				outline: none;\n");
      out.write("			}\n");
      out.write("		</style>\n");
      out.write("\n");
      out.write("		<script type=\"text/javascript\">		\n");
      out.write("			function toggle(divider) {\n");
      out.write("				var div = $(divider);\n");
      out.write("				if (div.attr('title') === 'Close') {\n");
      out.write("					div.attr('title', 'Open');\n");
      out.write("					div.parent().css('width', '1%');\n");
      out.write("					div.parent().next().css('width', '99%');\n");
      out.write("					div.css('background', 'url(\"images/showleft.png\")');\n");
      out.write("					$('#previews').hide();\n");
      out.write("					$('.heading').hide();\n");
      out.write("					$('#studyTable').hide();\n");
      out.write("					createEvent(\"ToolSelection\", {\n");
      out.write("               		 tool: 'close'\n");
      out.write("           			 });\n");
      out.write("				} else {\n");
      out.write("					div.attr('title', 'Close');\n");
      out.write("					div.parent().css('width', '255px');\n");
      out.write("					div.parent().next().css('width', '80%');\n");
      out.write("					div.css('background', 'url(\"images/hideleft.png\")');\n");
      out.write("					$('#previews').show();\n");
      out.write("					$('.heading').show();\n");
      out.write("					$('#studyTable').show();\n");
      out.write("					createEvent(\"ToolSelection\", {\n");
      out.write("               		 tool: 'close'\n");
      out.write("           			 });\n");
      out.write("				}\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			function showOtherStudies(patientID,selectedStudyId,dcmUrl,wadoUrl) {\n");
      out.write("				$.post(\"otherStudies.do\", {\n");
      out.write("					\"patientID\" : patientID,\n");
      out.write("					\"studyUID\" : selectedStudyId,\n");
      out.write("					\"dcmURL\" : dcmUrl					\n");
      out.write("				}, function(data) {\n");
      out.write("					$.each(data, function(i, study) {\n");
      out.write("						var div = document.createElement(\"div\");\n");
      out.write("						var url = \"Study.jsp?patient=\" + patientID + \"&study=\" + study[\"studyUID\"] + \"&dcmURL=\" + dcmUrl + \"&wadoUrl=\" + wadoUrl + \"&studyDesc=\" + study[\"dateDesc\"];\n");
      out.write("						jQuery(\"#otherStudies\").show();\n");
      out.write("						jQuery(\"#otherStudies\").load(url);\n");
      out.write("					});\n");
      out.write("				}, \"json\");\n");
      out.write("			}\n");
      out.write("\n");
      out.write("			function acc(acc1) {\n");
      out.write("            	/*acc1.next().toggle();          	\n");
      out.write("            	if(acc1.hasClass('open')) {\n");
      out.write("            		acc1.removeClass('open').addClass('close');\n");
      out.write("            	} else {\n");
      out.write("            		acc1.removeClass('close').addClass('open');\n");
      out.write("            	} */\n");
      out.write("            	if(acc1.hasClass(\"open\")) {\n");
      out.write("                	acc1.removeClass(\"open\").addClass(\"close\");\n");
      out.write("                	acc1.next().hide();\n");
      out.write("            	} else {\n");
      out.write("                	$(\".accordion\").next().hide();\n");
      out.write("                	$(\".accordion\").each(function() {\n");
      out.write("                    	if($(this).hasClass(\"open\")) {\n");
      out.write("                        	$(this).removeClass(\"open\").addClass(\"close\");\n");
      out.write("                    	}\n");
      out.write("                	});\n");
      out.write("                	acc1.removeClass(\"close\").addClass(\"open\");\n");
      out.write("                	acc1.next().show();\n");
      out.write("            	}\n");
      out.write("                	     	\n");
      out.write("            }\n");
      out.write("		</script>\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("    	<div title=\"Close\" style=\"width: 17px; height: 17px; cursor: pointer; float: right; background: url('images/hideleft.png');\" onclick=\"toggle(this);\"></div>\n");
      out.write("    \n");
      out.write("    	<div style=\"border: 2px solid #2A2A2A; height: 12%;\">\n");
      out.write("	        <div id=\"patName\" class=\"heading\" style=\"color: #FF8A00; padding: 2px 0 3px 3px; cursor: default;\" title=\"");
      out.print(patName);
      out.write('"');
      out.write('>');
      out.print(patName);
      out.write("</div>\n");
      out.write("	        <div id=\"patID\" class=\"heading\" style=\"color:#FF8A00; padding: 0 0 3px 3px; font-size: 15px !important;\">ID: ");
      out.print(patient);
      out.write("</div>\n");
      out.write("	        <table id=\"studyTable\" style=\"font-family: Arial; font-size:13px; width: 100%;color: #FF8A00; padding-bottom:3px; border: none;\">\n");
      out.write("				<tbody>\n");
      out.write("					<tr>\n");
      out.write("						<td colspan=\"2\"><div style=\"width:255px;\" class=\"content\">");
      out.print(studyDesc);
      out.write("</div></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.studyDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\n");
      out.write("						<td align=\"right\" style=\"padding-right: 15px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.totalSeries}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" Series</td>\n");
      out.write("					</tr>\n");
      out.write("				</tbody>\n");
      out.write("			</table>   \n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div id=\"previews\" style=\"overflow: auto; height: 88%; border-top: 2px solid black;width: 255px;\">\n");
      out.write("        	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("Study.jsp?patient=${encodedPatient}&patient1=${param.patient}&study=${param.study}&dcmURL=${param.dcmURL}&wadoUrl=${param.wadoUrl}&descDisplay=true&studyDesc=${param.studyDesc}&studyDate=${param.studyDate}&contentType=${param.contentType}&modaliy=${param.modality}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\n");
      out.write("        	<div id=\"otherStudiesInfo\" style=\"display: none;\"> </div>\n");
      out.write("        	<div id=\"otherModalities\"></div>\n");
      out.write("			<div id=\"otherStudies\" class='scrollable otherStudies-min'>	\n");
      out.write("        	</div>\n");
      out.write("        </div>     \n");
      out.write("	</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
